# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c7f42643aee96b883b616e62ad81d5a"
name = "profitable-franchise-app"
handle = "profitable-franchise-app-5"
application_url = "https://implies-haven-regards-breaking.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-433.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://implies-haven-regards-breaking.trycloudflare.com/auth/callback",
  "https://implies-haven-regards-breaking.trycloudflare.com/auth/shopify/callback",
  "https://implies-haven-regards-breaking.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
